In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [31]:
df = pd.read_csv('dataset/titanic.csv')
df= df.drop(columns=['name','sex'])
df.sample()

     survived  pclass   age  fare  sibsp  parch
370         0       1  47.0  38.5      0      0

In [32]:
df.shape

(714, 6)

In [33]:
df.isnull().sum()

survived    0
pclass      0
age         0
fare        0
sibsp       0
parch       0
dtype: int64

In [34]:
X = df.iloc[:,1:]
X.head()

   pclass   age     fare  sibsp  parch
0       3  22.0   7.2500      1      0
1       1  38.0  71.2833      1      0
2       3  26.0   7.9250      0      0
3       1  35.0  53.1000      1      0
4       3  35.0   8.0500      0      0

In [35]:
y = df.iloc[:,:1]
y.head()

   survived
0         0
1         1
2         1
3         1
4         0

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42, test_size=0.2)

In [37]:
X_train.shape

(571, 5)

In [46]:
np.mean(cross_val_score(LogisticRegression(),X,y.values.ravel(),scoring='accuracy',cv=20))

np.float64(0.7003968253968254)

### Feature Construction

In [48]:
X.sample()

     pclass   age  fare  sibsp  parch
493       3  21.0  16.1      0      0

In [49]:
X['Family_size']= X['sibsp'] +X['parch']+1

In [50]:
X.sample()

     pclass   age  fare  sibsp  parch  Family_size
149       3  40.0  15.5      1      1            3

In [51]:
def famfunc(num):
    if (num == 1):
        return 0 #alone
    elif(num >1 and num<=4):
        return 1 #small family
    else:
        return 2 #large family

In [52]:
X['Family_type']=X['Family_size'].apply(famfunc)

In [53]:
X.head()

   pclass   age     fare  sibsp  parch  Family_size  Family_type
0       3  22.0   7.2500      1      0            2            1
1       1  38.0  71.2833      1      0            2            1
2       3  26.0   7.9250      0      0            1            0
3       1  35.0  53.1000      1      0            2            1
4       3  35.0   8.0500      0      0            1            0

In [55]:
X = X.drop(columns=['sibsp','parch','Family_size'])
X.head()

   pclass   age     fare  Family_type
0       3  22.0   7.2500            1
1       1  38.0  71.2833            1
2       3  26.0   7.9250            0
3       1  35.0  53.1000            1
4       3  35.0   8.0500            0

In [57]:
np.mean(cross_val_score(LogisticRegression(),X,y.values.ravel(),scoring='accuracy',cv=20))

np.float64(0.7059126984126982)

### Feature Splitting

In [75]:
df = pd.read_csv('dataset/titanic.csv', usecols=['name'])
df.sample()

                            name
171  Givard, Mr. Hans Kristensen

In [76]:
#let's split the name
# we use .split() fn
# .split() returns splitted values in list in same column
# to make different columns .split( ,expand =True)

In [77]:
df[['Surname','Remaining_name']] = df['name'].str.split(',', expand=True)
df.sample()

                  name Surname Remaining_name
544  Dakic, Mr. Branko   Dakic     Mr. Branko

In [78]:
df[['Title','First_name']] = df['Remaining_name'].str.split('.',n=1, expand=True)
df.sample(5)

,name,Surname,Remaining_name,Title,First_name
687,"Hansen, Mr. Claus Peter",Hansen,Mr. Claus Peter,Mr,Claus Peter
711,"Graham, Miss. Margaret Edith",Graham,Miss. Margaret Edith,Miss,Margaret Edith
401,"Maioni, Miss. Roberta",Maioni,Miss. Roberta,Miss,Roberta
678,"Andersson, Master. Sigvard Harald Elias",Andersson,Master. Sigvard Harald Elias,Master,Sigvard Harald Elias
293,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",Warren,Mrs. Frank Manley (Anna Sophia Atkinson),Mrs,Frank Manley (Anna Sophia Atkinson)

In [ ]:
# we can also check where married or not